namespace WebAPIGenerator.ErrorHandling
{
    public static class TypeScriptModelGeneratorErrorMessages
    {
        public const string FailedToGenerateTypeScriptModels = "Failed to Generate TypeScript Models: ";

        public const string InvalidPath = "Invalid path for typescript autogenerated models";
    }
}
