import { observer } from "mobx-react-lite";
import { useEffect } from "react";
import { Tab } from "semantic-ui-react";
import { useStore } from "../../app/stores/store";
import { ProfileActivitiesFilterType } from "../../autogenerated/application/profiles/enums/profile-activities-filter-type.enum";
import ProfileEventsCardGrid from "./ProfileEventsCardGrid";

function ProfileEventsContent() {
    const {
        profileStore: { setActivitiesActiveTab, loadActivities, selectedProfile },
    } = useStore();

    useEffect(() => {
        loadActivities(selectedProfile.username, ProfileActivitiesFilterType.ImHosting);
    }, [loadActivities, selectedProfile]);

    const panes = [
        {
            menuItem: "I'm hosting",
            render: () => <ProfileEventsCardGrid />,
        },
        {
            menuItem: "Past events",
            render: () => <ProfileEventsCardGrid />,
        },
        {
            menuItem: "Upcoming events",
            render: () => <ProfileEventsCardGrid />,
        },
    ];

    return (
        <Tab.Pane>
            <Tab
                onTabChange={(e, data) => setActivitiesActiveTab(+data.activeIndex!)}
                enu={{ secondary: true, pointing: true }}
                panes={panes}
            />
        </Tab.Pane>
    );
}

export default observer(ProfileEventsContent);
