import { observer } from "mobx-react-lite";
import { Tab } from "semantic-ui-react";
import { ProfileApiModel } from "../../autogenerated/a-p-i/profiles/profile-api-model";

interface Props{
    profile: ProfileApiModel
}

function ProfileContent({profile}: Props) {
    const panes = [
        { menuItem: "About", render: () => <Tab.Pane>About Content</Tab.Pane> },
        { menuItem: "Events", render: () => <Tab.Pane>Events content</Tab.Pane> },
        { menuItem: "Followers", render: () => <Tab.Pane>Followers content</Tab.Pane> },
        { menuItem: "Following", render: () => <Tab.Pane>Following content</Tab.Pane> },
    ];

    return <Tab menu={{ fluid: true, vertical: true, tabular: "right" }} panes={panes} />;
}

export default observer(ProfileContent);
