import { observer } from "mobx-react-lite";
import { Link } from "react-router-dom";
import { Card, Image, Icon } from "semantic-ui-react";
import { ProfileApiModel } from "../../autogenerated/a-p-i/profiles/profile-api-model";

interface Props {
    profile: ProfileApiModel;
}

function ProfileCard({ profile }: Props) {
    function truncate(str: string | undefined) {
        if (str) {
            return str.length > 40 ? str.substring(0, 37) + '...' : str;
        }
    }

    return (
        <Card as={Link} to={`/profile/${profile.username}`}>
            <Image src={profile.pictureUrl || "/assets/user.png"} wrapped ui={false} />
            <Card.Content>
                <Card.Header>{profile.displayName}</Card.Header>
                <Card.Description>{truncate(profile.bio)}</Card.Description>
            </Card.Content>
            <Card.Content extra>
                <Icon name="user" />
                22 Friends
            </Card.Content>
        </Card>
    );
}

export default observer(ProfileCard);
