import { Form, Formik } from "formik";
import { observer } from "mobx-react-lite";
import { Button, Container, Divider, Header } from "semantic-ui-react";
import ReactivitiesTextArea from "../../app/common/form/ReactivitiesTextArea";
import ReactivitiesTextInput from "../../app/common/form/ReactivitiesTextInput";
import { useStore } from "../../app/stores/store";
import { ProfileApiModel } from "../../autogenerated/a-p-i/profiles/profile-api-model";
import * as Yup from "yup";


function ProfileDetailsEditForm() {
    const { profileStore } = useStore();

    function handleFormSubmit(profile: ProfileApiModel) {
        profileStore.updateDetails(profile).then(() => profileStore.setEditDetailsMode(false));
    }

    const validationSchema = Yup.object({
        displayName: Yup.string().required("Display Name is required"),
        email: Yup.string().required("Email is required"),
    });

    return (
        <>
            <Header
                icon="user"
                as="h3"
                content={`About ${profileStore.selectedProfile?.displayName}`}
                style={{ paddingBottom: "25px" }}
            />
            {profileStore.editDetailsMode ? (
                <Formik
                    enableReinitialize
                    validationSchema={validationSchema}
                    initialValues={profileStore.currentProfile!}
                    onSubmit={(values) => handleFormSubmit(values)}>
                    {({ handleSubmit, isSubmitting, isValid, dirty }) => (
                        <Form className="ui form" onSubmit={handleSubmit} autoComplete="off">
                            <ReactivitiesTextInput
                                placeholder={"Display Name"}
                                name={"displayName"}
                                label={"Display Name"}
                            />
                            <ReactivitiesTextInput
                                placeholder={"Email"}
                                name={"email"}
                                label={"Email"}
                            />
                            <ReactivitiesTextArea
                                placeholder={"Bio"}
                                name={"bio"}
                                rows={3}
                                label={"Bio"}
                            />
                            <Button
                                loading={isSubmitting}
                                disabled={!dirty || !isValid || profileStore.loading}
                                type="submit"
                                positive>
                                Submit
                            </Button>
                            <Button
                                disabled={isSubmitting}
                                onClick={() => profileStore.setEditDetailsMode(false)}>
                                Cancel
                            </Button>
                        </Form>
                    )}
                </Formik>
            ) : (
                <div>
                    <Container>
                        <Header as="h4" content="Email" />
                        <Divider />
                        <p>{profileStore.selectedProfile?.email}</p>
                        <Header as="h4" content="Bio" />
                        <Divider />
                        <p
                            style={{
                                fontStyle: profileStore.selectedProfile?.bio ? "normal" : "italic",
                            }}>
                            {profileStore.selectedProfile?.bio || "Tell us something about yourself...."}
                        </p>
                    </Container>
                    {profileStore.isCurrentProfile && (
                        <Button
                            style={{ marginTop: "20px" }}
                            content="Edit Profile"
                            onClick={() => profileStore.setEditDetailsMode(true)}
                        />
                    )}
                </div>
            )}
        </>
    );
}

export default observer(ProfileDetailsEditForm);
