import { observer } from "mobx-react-lite";
import { SyntheticEvent } from "react";
import { Button, Reveal } from "semantic-ui-react";
import { useStore } from "../../app/stores/store";
import { ProfileApiModel } from "../../autogenerated/a-p-i/profiles/profile-api-model";

interface Props {
    profile: ProfileApiModel;
}

function ProfilesFollowButton({ profile }: Props) {
    const {
        profileStore: { updateFollowing, currentProfile, loading },
    } = useStore();

    if (profile.username === currentProfile.username) return null;

    function handleFollow(e: SyntheticEvent, username: string) {
        e.preventDefault();
        updateFollowing(username);
    }

    return (
        <Reveal animated="move">
            <Reveal.Content visible style={{ width: "100%" }}>
                <Button
                    fluid
                    color="teal"
                    content={profile.following ? "Following" : "Not Following"}
                />
            </Reveal.Content>
            <Reveal.Content hidden style={{ width: "100%" }}>
                <Button
                    fluid
                    basic
                    loading={loading}
                    color={profile.following ? "red" : "green"}
                    content={profile.following ? "Unfollow" : "Follow"}
                    onClick={(e) => handleFollow(e, profile.username)}
                />
            </Reveal.Content>
        </Reveal>
    );
}

export default observer(ProfilesFollowButton);
