import { Fragment, useEffect, useState } from 'react';
import './App.css';
import { Container } from 'semantic-ui-react';
import { ActivityResponse as Activity, ActivityResponse } from '../../autogenerated/models/activities/response/activity-response';
import NavBar from './NavBar';
import ActivityDashboard from '../../features/activities/dashboard/ActivityDashboard';
import agent from '../api/agent';

function App() {
  const [activities, setActivities] = useState<Activity[]>([]);
  const [selectedActivity, setSelectedActivity] = useState<Activity | undefined>(undefined);
  const [editMode, setEditMode] = useState(false);

  useEffect(() => {
    agent.Activities.list().then(data => {
        const tempActivities: ActivityResponse[] = [];

        data.forEach(activity => {
          activity.date = activity.date.split('T')[0];
          tempActivities.push(activity);
        })

        setActivities(tempActivities);
      });
  }, [activities]);

  function handleSelectActivity(id: number) {
    setSelectedActivity(activities.find(a => a.id === id));
  }

  function handleCancelSelectedActivity() {
    setSelectedActivity(undefined);
  }

  function handleFormOpen(id?: number) {
    id ? handleSelectActivity(id) : handleCancelSelectedActivity();
    setEditMode(true);
  }

  function handleFormClose() {
    setEditMode(false);
  }

  function handleCreateOrEditActivty(activity: Activity) {
    activity.id
      ? setActivities([...activities.filter(a => a.id !== activity.id), activity])
      : setActivities([...activities, activity])
    setEditMode(false);
    setSelectedActivity(activity);
  }

  function handleDeleteActivity(id: number){
    setActivities([...activities.filter(a => a.id !== id)])
  }

  return (
    <Fragment >
      <NavBar openForm={handleFormOpen} />
      <Container style={{ marginTop: '7em' }}>
        <ActivityDashboard
          activities={activities}
          selectedActivity={selectedActivity}
          selectActivity={handleSelectActivity}
          cancelSelectActivity={handleCancelSelectedActivity}
          editMode={editMode}
          openForm={handleFormOpen}
          closeForm={handleFormClose}
          createOrEdit={handleCreateOrEditActivty}
          deleteActivity = {handleDeleteActivity}
        />
      </Container>
    </Fragment>
  );
}

export default App;
