import { Grid, List } from "semantic-ui-react";
import { Activity } from "../../../autogenerated/domain/activity";

interface Props{
    activities: Activity[];
}

export default function ActivityDashboard(props: Props) {
    return (
        <Grid>
            <Grid.Column width='10'>
                <List>
                    {props.activities.map(activity => (
                        <List.Item key={activity.id}>
                            {activity.title}
                        </List.Item>
                    ))}
                </List>
            </Grid.Column>
        </Grid>
    )
}