import { observer } from "mobx-react-lite";
import { Link } from "react-router-dom";
import { List, Image, Label, Popup } from "semantic-ui-react";
import { ProfileApiModel } from "../../../autogenerated/a-p-i/common/identity/models/profile-api-model";
import ProfileCard from "../../profiles/ProfileCard";

interface Props {
    attendees: ProfileApiModel[];
}

function ActivityListItemAttendees({ attendees }: Props) {
    if (attendees.length > 0) {
        return (
            <List horizontal>
                {attendees.map((a) => (
                    <Popup
                        hoverable
                        key={a.username}
                        trigger={
                            <List.Item key={a.username} as={Link} to={`/profiles/${a.username}`}>
                                <Image size="mini" circular src={a.image || "/assets/user.png"} />
                            </List.Item>
                        }>
                        <Popup.Content>
                            <ProfileCard profile={a} />
                        </Popup.Content>
                    </Popup>
                ))}
            </List>
        );
    }

    return <Label>No attendees at this time.</Label>;
}

export default observer(ActivityListItemAttendees);
