import { Button, Item, Label, Segment } from "semantic-ui-react";
import { ActivityResponse as Activity } from "../../../autogenerated/models/activities/response/activity-response";

interface Props{
    activities: Activity[];
    selectActivity: (id: number) => void;
    deleteActivity: (id: number) => void;
}

export default function ActivityList(props: Props){
    return (
        <Segment>
            <Item.Group divided>
                {props.activities.map(activity => (
                    <Item key={activity.id}>
                        <Item.Content>
                            <Item.Header as='a'>{activity.title}</Item.Header>
                            <Item.Meta>{activity.date}</Item.Meta>
                            <Item.Description>
                                <div>{activity.description}</div>
                                <div>{activity.city}, {activity.venue}</div>
                            </Item.Description>
                            <Item.Extra>
                                <Button onClick={() => props.selectActivity(activity.id)} floated='right' content='View' color='blue'/>
                                <Button onClick={() => props.deleteActivity(activity.id)} floated='right' content='Delete' color='red'/>
                                <Label basic content={activity.category}/>
                            </Item.Extra>
                        </Item.Content>
                    </Item>
                ))}
            </Item.Group>
        </Segment>
    )
}