import { observer } from "mobx-react-lite";
import { Link } from "react-router-dom";
import { List, Image, Label } from "semantic-ui-react";
import { ProfileApiModel } from "../../../autogenerated/a-p-i/common/identity/models/profile-api-model";

interface Props {
    attendees: ProfileApiModel[];
}

function ActivityListItemAttendees({ attendees }: Props) {
    if (attendees.length > 0) {
        return (
            <List horizontal>
                {attendees.map((a) => (
                    <List.Item key={a.username} as={Link} to={`/profiles/${a.username}`}>
                        <Image size="mini" circular src={a.image || "/assets/user.png"} />
                    </List.Item>
                ))}
            </List>
        );
    }

    return <Label>No attendees at this time.</Label>
}

export default observer(ActivityListItemAttendees);
