import React from "react";
import { Link } from "react-router-dom";
import { Button, Icon, Item, Segment } from "semantic-ui-react";
import { ActivityApiModel } from "../../../autogenerated/a-p-i/activities/models/activity-api-model";
import {format} from "date-fns"
import { reactivitiesDateTimeFormat } from "../../../app/common/constants/GlobalConstants";


interface Props {
    activity: ActivityApiModel;
}

export default function ActivityListItem({ activity }: Props) {
    return (
        <Segment.Group>
            <Segment>
                <Item.Group>
                    <Item>
                        <Item.Image
                            style={{ marginBottom: 3 }}
                            size="tiny"
                            circular
                            src="/assets/user.png"
                        />
                        <Item.Content>
                            <Item.Header as={Link} to={`/activities/${activity.id}`}>
                                {activity.title}
                            </Item.Header>
                            <Item.Description>Hosted by Bob</Item.Description>
                        </Item.Content>
                    </Item>
                </Item.Group>
            </Segment>
            <Segment>
                <span>
                    <Icon name="clock" /> {format(activity.date, reactivitiesDateTimeFormat)}
                    <Icon name="marker" /> {activity.venue}
                </span>
            </Segment>
            <Segment clearing>
                <span>{activity.description}</span>
                <Button
                    as={Link}
                    to={`/activities/${activity.id}`}
                    color="teal"
                    floated="right"
                    content="View"
                />
            </Segment>
        </Segment.Group>
    );
}
