import { makeAutoObservable, reaction } from "mobx";
import { ExceptionResponseModel } from "../../autogenerated/a-p-i/common/middleware/error-handling/exception-response-model";

export default class CommonStore {
    error: ExceptionResponseModel | null = null;
    token: string | null = window.localStorage.getItem("userToken");
    appLoaded = false;

    constructor() {
        makeAutoObservable(this);

        reaction(
            () => this.token,
            (token) => {
                if (token) {
                    window.localStorage.setItem("userToken", token);
                    return;
                }

                window.localStorage.removeItem("userToken");
            }
        );
    }

    setServerError = (error: ExceptionResponseModel) => {
        this.error = error;
    };

    setToken = (token: string | null) => {
        this.token = token;
    };

    setAppLoaded = () => {
        this.appLoaded = true;
    };
}
