import { makeAutoObservable } from "mobx";
import { ExceptionResponseModel } from "../../autogenerated/a-p-i/common/middleware/error-handling/exception-response-model";

export default class CommonStore {
    error: ExceptionResponseModel | null = null;

    constructor() {
        makeAutoObservable(this);
    }

    setServerError = (error: ExceptionResponseModel) => {
        this.error = error;
    };
}
