import { makeAutoObservable } from "mobx";
import { ProfileApiModel } from "../../autogenerated/a-p-i/profiles/profile-api-model";
import agent from "../api/agent";
import { store } from "./store";

export default class ProfileStore {
    private profile: ProfileApiModel | null = null;
    private selectedProfile: ProfileApiModel | null = null;
    loadingUser = false;
    uploading = false;

    constructor() {
        makeAutoObservable(this);
    }

    get currentProfile() {
        return this.profile;
    }

    get isLoggedIn() {
        return !!this.profile;
    }

    loadProfile = async (username: string) => {
        this.loadingUser = true;
        try {
            const profile = await agent.Profiles.get(username);

            this.setSelectedProfile(profile);
        } catch (error) {
            console.log(error);
        } finally {
            this.setLoadingUser(false);
        }
    };

    loadCurrentProfile = async () => {
        this.loadingUser = true;
        try {
            const profile = await agent.Profiles.getCurrent();

            this.setCurrentProfile(profile);
        } catch (error) {
            console.log(error);
        } finally {
            this.setLoadingUser(false);
        }
    };

    uploadProfilePicture = async (file: Blob) => {
        this.setUploading(true);
        try{
            const response = await agent.Profiles.uploadPhoto(file);
            const pictureUrl = response.data;

            this.setProfilePicture(pictureUrl)
        }catch(error){
            console.log(error)
        }finally{
            this.setUploading(false);
        }
    };

    deleteProfilePicture = async () => {
        this.setUploading(true);
        try{
            await agent.Profiles.deletePhoto();

            this.setProfilePicture('')
        }catch(error){
            console.log(error)
        }finally{
            this.setUploading(false);
        }
    };

    isActivityHost = (activityHostUsername: string | undefined) => {
        return this.profile?.username === activityHostUsername;
    };

    isGoingToActivity = (activityId: number) => {
        return store.activityStore.activitiesRegistry
            .get(activityId)
            ?.attendees.some((a) => a.username === this.profile?.username);
    };

    setCurrentProfile = (profile: ProfileApiModel | null) => {
        this.profile = profile;
    };

    private setProfilePicture = (pictureUrl: string) => {
        this.currentProfile!.pictureUrl = pictureUrl;
    }

    private setUploading = (state: boolean) => {
        this.uploading = state;
    };

    private setSelectedProfile = (selectedProfile: ProfileApiModel | null) => {
        this.selectedProfile = selectedProfile;
    };

    private setLoadingUser = (state: boolean) => {
        this.loadingUser = state;
    };
}
