import { makeAutoObservable } from "mobx";
import { history } from "../..";
import { LoginApiModel } from "../../autogenerated/a-p-i/common/identity/models/login-api-model";
import { RegisterApiModel } from "../../autogenerated/a-p-i/common/identity/models/register-api-model";
import agent from "../api/agent";
import { store } from "./store";

export default class UserStore {

    constructor() {
        makeAutoObservable(this);
    }

    login = async (creds: LoginApiModel) => {
        try {
            const token = await agent.Accounts.login(creds);

            this.setCurrentUserAndCloseModal(token);
        } catch (error) {
            console.log(error);
        }
    };

    register = async (details: RegisterApiModel) => {
        try {
            const token = await agent.Accounts.register(details);

            this.setCurrentUserAndCloseModal(token);
        } catch (error) {
            console.log(error);
        }
    };

    logout = () => {
        store.commonStore.setToken(null);
        window.localStorage.removeItem("userToken");
        store.profileStore.setProfile(null);
        history.push("/");
    };

    private setCurrentUserAndCloseModal = async (token: string) => {
        if (token) {
            store.commonStore.setToken(token);
            await store.profileStore.loadCurrentProfile();
        }

        history.push("/activities");
        store.modalStore.closeModal();
    };
}
