import { makeAutoObservable } from "mobx";
import { LoginApiModel } from "../../autogenerated/a-p-i/common/identity/models/login-api-model";
import { UserApiModel } from "../../autogenerated/a-p-i/common/identity/models/user-api-model";
import agent from "../api/agent";


export default class UserStore {
    user: UserApiModel | null = null;

    constructor() {
        makeAutoObservable(this);
    }

    get IsLoggedIn() {
        return !!this.user;
    }

    login = async (creds: LoginApiModel) => {
        try {
            const user = await agent.Accounts.login(creds);
            console.log(user);
        } catch (error) {
            console.log(error);
        }
    };
}